### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by Zcaic** [esa/pygmo2#100]
when i use conda install pygmeo successfully, i  found it can work but there is no code intelligence hints in VS code, there is some way to solve it?
thanks!

**Comment by bluescarni** [comment]
This looks like it is a VS code question, rather than a pygmo question. On Linux, the clangd VS code plugin works well for me, see:

https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd

Read carefully the installation instructions - in particular, you need to invoke CMake with the  ``-DCMAKE_EXPORT_COMPILE_COMMANDS=1`` option. I also *think* that your build directory needs to be called ``build`` in order for everything to work out of the box, but I am not 100% sure.

Closing the report.

**Comment by Zcaic** [comment]
Thank you ,I will give it a try.
