### ISSUE TITLE
Unable to install pygmo using pip

### ISSUE THREAD

**Issue by dkrevana** [esa/pygmo2#146]
**Describe the bug**
Installation of pygmo using pip fails with following error message
```
> pip install --no-cache-dir pygmo 
Collecting pygmo
  Downloading pygmo-v2.19.0.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 24.7 MB/s eta 0:00:00
ERROR: pygmo from https://files.pythonhosted.org/packages/e2/12/090ba61479f60d5177a0048736d09dc028b2d65063ed44cb952df506336f/pygmo-v2.19.0.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**To Reproduce**
1. create a virtual environment with python 3.11.1
2. upgrade pip
3. run `pip install pygmo`

**Environment (please complete the following information):**
 - OS: Linux
 - Installation method:  pip
 - Version: latest

**Additional context**

**Comment by bluescarni** [comment]
@dkrevana what Linux distribution is this?

**Comment by dkrevana** [comment]
> @dkrevana what Linux distribution is this?

Here is the OS information
```
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP5
Release:        12.5
```

**Comment by bluescarni** [comment]
I am reading here:

https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=12.5&arch=x86_64&query=glibc&module=

that apparently the GLIBC version is 2.22. This is too old for the binary wheels of pygmo, which require GLIBC>=2.28.

You have a few options:

- update to a more recent Linux distribution,
- install pygmo within a docker container,
- attempt an installation via conda rather than pip.

Closing the issue as it is not pygmo related.
