### ISSUE TITLE
[BUG] pyproject.toml and setup.py missing?

### ISSUE THREAD

**Issue by danihae** [esa/pygmo2#152]
When I install pygmo via pip `pip install pygmo`, I get this error message, suggesting that a setup.py and pyproject.toml file are missing.

ERROR: pygmo from https://files.pythonhosted.org/packages/e2/12/090ba61479f60d5177a0048736d09dc028b2d65063ed44cb952df506336f/pygmo-v2.19.0.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Thanks for your help!

**Comment by bluescarni** [comment]
Hi @danihae 

pygmo does not have a fully-fledged and standard-compliant ``pip``-based build system. We have only the bare minimum to produce binary wheels, which are the only supported types of ``pip`` packages.

We would need to understand why ``pip install pygmo`` attempts to use the source distribution rather than the binary wheels. Specifically:

- are you on Linux? We produce binary wheels only for x86-64 and arm64 Linux platforms, OSX and Windows are not supported;
- if you are on Linux, what kind of distribution are you using? If it is a very old distribution, the binary wheels won't work and ``pip`` will attempt an installation from source instead.

Finally, I would suggest you to use ``conda`` rather than ``pip``: on ``conda`` we have up-to-date packages for all major operating systems and platforms.

**Comment by danihae** [comment]
Hi @bluescarni

Thanks for the quick response! I use OSX. I now tried conda and it's working well.

**Comment by electric-vehicle-optimisation** [comment]
Yeah so for Windows users that already have their pip environment set up, Pygmo is basically not an option, unless you want to go through some insane amount of trouble.

**Comment by JacquesWust** [comment]
Yeah so for Windows users that already have their pip environment set up, Pygmo is basically not an option, unless you want to go through some insane amount of trouble.

**Comment by gituser789** [comment]
Would it be possible to provide a `pip` compatible package for `linux` users? May it is possible to restrict the operating system inside `pyproject.toml`.

**Comment by MLopez-Ibanez** [comment]
I would like to add `pygmo` to these benchmarks: https://multi-objective.github.io/moocore/python/#benchmarks but the package cannot be installed with `pip`.
