### ISSUE TITLE
Wheel for Python 3.8

### ISSUE THREAD

**Issue by DavidWalz** [esa/pygmo2#19]
Could you please provide wheels for python 3.8 (linux)?

**Comment by darioizzo** [comment]
Are the 38 issues on ipyparallel soled? I thought we were not releasing the 38 wheels for that reason.

**Comment by bluescarni** [comment]
What were the issues again? I cannot recall exactly. I thought that the problem was the lack of a conda package, but it seems like it is available now:

https://anaconda.org/conda-forge/ipyparallel/files

And the pip package for ipyparallel seems to be independent of the Python version:

https://pypi.org/project/ipyparallel/#files

In any case, if there are runtime problems with ipyparallel I think we can just disable the ipyparallel testing bits in the docker script in the meantime.

**Comment by darioizzo** [comment]
ok, will  make a PR and see.

**Comment by bluescarni** [comment]
py38 wheels have been implemented in #20, and they will be part of the upcoming release. Closing this.
