### ISSUE TITLE
The PyPI site doesn't contain the source tarball

### ISSUE THREAD

**Issue by yurivict** [esa/pygmo2#53]
https://pypi.org/project/pygmo/#files

**Comment by darioizzo** [comment]
Closing this as the pybind11 library (.so) cannot be packaged as source as I understand this suggestion. A binary wheel must be created instead as done now again #117.

**Comment by yurivict** [comment]
> Closing this as the pybind11 library (.so) cannot be packaged as source as I understand this suggestion.

pybind11 library (.so) is pre-installed and is not meant to be packaged by pygmo2.

I don't understand how does this prevent tarball distribution.

**Comment by darioizzo** [comment]
If we run also ``python setupy.py sdist`` the tarball will contain a ``pygmo.so`` compiled for a specific architecture only and linking to specific library names (and version). 

When a user would then use such a tarball in his system, the library will likely be incompatible as the architecture may be different. And also in case we would produce one tarball per architecture, the libraries linked to the ``pygmo.so`` will have differen version in the final host system.

This is infact the issue solved by producing binary wheels and repairing them so that all libraries are also packaged in the binary file and will be compatible.

**Comment by yurivict** [comment]
@darioizzo The source tarball is not supposed to contain any binaries. It should only contain the code that is sufficient to rebuild binaries, not binaries themselves.

**Comment by darioizzo** [comment]
Ok but is that not available already in github? like here: https://github.com/esa/pygmo2/releases .... 
I might be confused, but are you suggesting to put that tarball also in PyPi?

**Comment by yurivict** [comment]
That's what most projects are doing, for example https://pypi.org/project/pybind11/#files

https://github.com/esa/pygmo2/releases is auto-generated from git on the fly by GitHub.

**Comment by darioizzo** [comment]
I am not familiar with best practices in PyPi, so I trust you there. So it would be enough (during a release build) to tar the cloned pygmo2 repo and then upload it via twine to PyPi? 

If you confirm, @yurivict we can easily do that for the next releases .....

**Comment by bluescarni** [comment]
@yurivict in order to produce working ``sdist`` packages we need to use something like scikit-build

https://scikit-build.readthedocs.io/en/latest/index.html

with which I had some success in other CMake-based projects. Unfortunately, with the pending removal of distutils in Python 3.12, ``scikit-build`` is being deprecated in favour of

https://github.com/scikit-build/scikit-build-core

which however is not ready yet. Thus, we plan to add ``sdist`` support when the waters have calmed a bit.

**Comment by yurivict** [comment]
> If you confirm, @yurivict we can easily do that for the next releases .....

Yes, a simple tarball of the cloned directory is what people put there.

**Comment by darioizzo** [comment]
To summarize:
@bluescarni solution (using sdist properly in connection to [scikit-build-core](https://github.com/scikit-build/scikit-build-core) used in setup.py  would ensure that after typing something like ``pip install pip install pygmo2-sdist.tar.gz`` the pygmo2 code is compiled locally on the user machine (provided the user has installed all dependencies, including pagmo). For this we must wait September when the scikit-build-core project is stable and usable long term)

 @yurivict solution only uploads the cloned repository. I could add this easily also to the current CI manylinux pipelines.
 The user would then have to manually untar and call cmake; make; install in a build directory.

Frankly though, I fail to see much use to both solutions as users who must compile the code are anyway better off doing so checking the github repository.

**Comment by darioizzo** [comment]
added as per @yurivict suggestion. should appear in the next release.
